Repository bertugarangou/calcot-intel-ligent, pull requests merged in 2021-10, with the labels that each got.

#4 Revert "Traducció dels missatges per petició"
  Twitter_per_Calçot_intel_ligent.py
Labels: enhancement, hacktoberfest

#5 Update LICENSE
  LICENSE
Labels: documentation, enhancement, hacktoberfest, hacktoberfest-accepted

#6 unió
  README.md
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#7 format
  README.md
Labels: hacktoberfest, hacktoberfest-accepted
